# Режим синхронизации ролей:
# "rcon" (роли синхронизируются через RCON команды с сайта и хранятся в players.yml)
# "db" (роли считываются напрямую из базы данных сайта users.db)
sync-mode: "rcon"
database-path: "plugins/BlockCommand/users.db"

# Язык по умолчанию ("ru" или "en")
default-language: "ru"

# Список разрешенных команд для обычных игроков (без косой черты /)
# Команды должны быть записаны в нижнем регистре.
allowed-commands:
  - msg
  - me
  - try
  - login
  - changepassword
  - register
  - help

# Дополнительные роли (права) и команды, к которым они дают доступ
roles:
  detective:
    # Игрок с этим правом получит доступ к командам роли
    permission: "blockcommand.role.detective"
    # Дополнительные разрешенные команды для роли.
    # Если указана только команда (например, "spawn"), то разрешена вся команда.
    # Если указана команда с аргументами (например, "co i"), то разрешено выполнение
    # этой команды, если её начало совпадает с указанной строкой (регистр не важен).
    commands:
      - "co i"
      - "co inspect"

# Настройки прав доступа
permissions:
  # Право, позволяющее обходить блокировку и использовать любые команды
  bypass: "blockcommand.bypass"
  # Право для перезагрузки конфигурации (/blockcommand reload)
  admin: "blockcommand.admin"
